services:
    app:
        image: ${APP_NAME:-symfony}-app-dev:local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: app_dev
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        env_file:
            - ${ENV_FILE:-.env}
