services:
    app:
        image: ${APP_NAME:-symfony}-app-dev:local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: app_dev
        env_file:
            - ${ENV_FILE:-.env}
    web:
        image: ${APP_NAME:-symfony}-web-dev:local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: web_dev
        ports:
            - ${APP_PORT:-8000}:80
        depends_on:
            - app
