services:
    app:
        image: symfony-app:local
        build:
            target: app
    web:
        image: symfony-web:local
        build:
            args:
                ASSETS_IMAGE: "${APP_NAME}-app:local"
            target: web
