services:
    app:
        build:
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
        environment:
            APP_ENV: dev
            OPCACHE_VALIDATE_TIMESTAMPS: 1
            XDEBUG_MODE: develop,debug
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./app:/var/www/html:rw,cached
    web:
        volumes:
            - ./app/public:/var/www/html/public:ro,delegated
