---
name: Build Docker images
on:
    push:
        branches:
            - 'main'
    workflow_dispatch:
jobs:
    build_and_push:
        name: 'Build & Push'
        runs-on: ubuntu-latest
        steps:
            - name: 'Set up Docker BuildX'
              uses: docker/setup-buildx-action@v3
              with:
                  version: latest

            - name: 'Log into GitHub Container Registry'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: 'Build and push image'
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/amd64
                  context: .
                  file: ./docker/Dockerfile
                  target: app
                  cache-from: type=registry,ref=ghcr.io/robmeijer/docker-app:latest
                  cache-to: type=inline
                  pull: true
                  push: true
                  tags: |
                      ghcr.io/robmeijer/docker-app:release-${{ github.run_number }}
                      ghcr.io/robmeijer/docker-app:latest
